source 'https://rubygems.org'

gem 'rails', '3.2.9'
gem 'mysql2'
gem 'jquery-rails'
gem 'haml-rails'
gem 'json'
gem 'fancybox-rails'
gem 'ransack'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
  gem 'compass-rails'
end